coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
comment:                  # this is a top-level key
  layout: "diff, flags, files"
  behavior: default
parsers:
  javascript:
    enable_partials: yes
#comment:
#  layout: "diff,flags,tree,betaprofiling"
#  show_critical_paths: true
