version: '3.8'

services:
  db-challenge-prod:
    image: postgres:alpine
    container_name: db-challenge-prod
    restart: always
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5437:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  server-challenge-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: server-challenge-prod
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=8081
    ports:
      - '8081:8080'
    depends_on:
      db-challenge-prod:
        condition: service_healthy
    links:
      - db-challenge-prod

volumes:
  db-challenge-prod:
